version: '3'
# Having an issue with the remote_worker needing to spawn a few seconds after the hazelcast server is up.
#
# TO USE THIS COMBINATION, ADD THIS TO BAZELRC
#  build --remote_cache=172.25.0.101:8085


services:
  hazelcast_cache:
    image: murtis/hazelcast:latest
    networks:
      bazelcast:
        ipv4_address: 172.25.0.102
# NOT QUITE WORKING YET
# NOT QUITE WORKING YET
# NOT QUITE WORKING YET
# NOT QUITE WORKING YET
# NOT QUITE WORKING YET
# NOT QUITE WORKING YET
  management_server:
    image: hazelcast/management-center:latest
    ports:
      - "8086:8086"
    networks:
      bazelcast:
        ipv4_address: 172.25.0.103

  remote_worker:
    image: murtis/bazel_remote_worker:latest
    ports:
      - "8085:8085"
    networks:
      bazelcast:
        ipv4_address: 172.25.0.101
    environment:
      LISTEN_PORT: 8085
      HAZELCAST_SEVER: 172.25.0.102
    depends_on:
      - hazelcast_cache
      - management_server



networks:
  bazelcast:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
